<?php 
class Mlaporan extends CI_Model{

    public function __construct()
    {
        parent::__construct();
        $this->load->database();
    }

	// laporan bulanan infrastruktur
    public function LBInfrastruktur($tglawal, $tglakhir){
		$sql = $this->db->query("SELECT
		EDP.NAMA_PETUGAS As NAMA_PETUGAS,
		EDP.PETUGAS As NOMOR_INDUK,
		EDCA.NO_COMPLAIN As NO_COMPLAIN,
		EDCA.KODEDIV As KODEDIV,
		EDCA.KODE_UNIT As KODE_UNIT,
		EDCA.TGL As TGL_COMPLAIN,
		EDCA.URAIAN As URAIAN,
		EDSA.NO_SPK As NO_SPK,
		EDSA.TGL_SPK As TGL_SPK,
		EDSA.JAM_SPK As JAM_SPK,
		EDCA.TGL_SAH As TGL_SAH,
		EDCA.TGL_SAH As JAM_SAH,
		EDSB.PEKERJAAN As PEKERJAAN
		FROM ED_PETUGAS EDP
		JOIN ED_SPKC EDSC ON EDP.PETUGAS=EDSC.PETUGAS
		JOIN ED_SPKA EDSA ON EDSC.NO_SPK=EDSA.NO_SPK
		JOIN ED_SPKB EDSB ON EDSA.NO_SPK=EDSB.NO_SPK
		JOIN ED_SPKD EDSD ON EDSA.NO_SPK=EDSD.NO_SPK
		JOIN ED_COMPA EDCA ON EDSA.NO_COMPLAIN=EDCA.NO_COMPLAIN
		WHERE EDSA.TGL_SPK >= to_date('".$tglawal."', 'MM/DD/YYYY') and EDSA.TGL_SPK <= to_date('".$tglakhir."', 'MM/DD/YYYY') + INTERVAL '1' DAY
		");

		

		return $sql;
	}

	// laporan Kegiatan Infrastruktur
	public function LKInfrastruktur($tglawal, $tglakhir){
		$sql = $this->db->query("SELECT
		EDP.NAMA_PETUGAS As NAMA_PETUGAS,
		EDP.PETUGAS As NOMOR_INDUK,
		EDCA.NO_COMPLAIN As NO_COMPLAIN,
		EDCA.KODEDIV As KODEDIV,
		EDCA.KODE_UNIT As KODE_UNIT,
		EDCA.TGL As TGL_COMPLAIN,
		EDCA.URAIAN As URAIAN,
		EDSA.NO_SPK As NO_SPK,
		EDSA.TGL_SPK As TGL_SPK,
		EDSA.JAM_SPK As JAM_SPK,
		EDCA.TGL_SAH As TGL_SAH,
		EDCA.TGL_SAH As JAM_SAH,
		EDSB.PEKERJAAN As PEKERJAAN
		FROM ED_PETUGAS EDP
		JOIN ED_SPKC EDSC ON EDP.PETUGAS=EDSC.PETUGAS
		JOIN ED_SPKA EDSA ON EDSC.NO_SPK=EDSA.NO_SPK
		JOIN ED_SPKB EDSB ON EDSA.NO_SPK=EDSB.NO_SPK
		JOIN ED_SPKD EDSD ON EDSA.NO_SPK=EDSD.NO_SPK
		JOIN ED_COMPA EDCA ON EDSA.NO_COMPLAIN=EDCA.NO_COMPLAIN
		WHERE EDCA.TGL >= to_date('".$tglawal."', 'MM/DD/YYYY') and EDCA.TGL <= to_date('".$tglakhir."', 'MM/DD/YYYY') + INTERVAL '1' DAY
		");

		

		return $sql;
	}

    
}
?>
